{"variants":[{"paths":["\/documentation\/tpay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tpay"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[[]]},"metadata":{"roleHeading":"Framework","role":"collection","modules":[{"name":"Tpay"}],"externalID":"Tpay","title":"Tpay","symbolKind":"module"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"The Tpay SDK empowers your app to seamlessly integrate Tpay’s payment functionalities, providing a comprehensive and developer-friendly solution for managing payments. By utilizing the SDK’s capabilities, you can offer your users a secure, convenient, and reliable payment experience within your app.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.tpay.sdk\/documentation\/Tpay"},"topicSections":[{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics"],"title":"Getting started","anchor":"Getting-started"},{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments"],"title":"Use cases","anchor":"Use-cases"},{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Changelog","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/VersionSupport"],"generated":true,"title":"Articles","anchor":"Articles"},{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCardDelegate","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AliasRegistrationStatus","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/MerchantDetailsProvider","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ModuleError","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentDelegate","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentResult","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Presentable","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Recursive","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SSLCertificatesProvider","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Transaction","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TransactionStatusObserver","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/WebViewPaymentDelegate"],"generated":true,"title":"Protocols","anchor":"Protocols"},{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Address","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPaymentMethods","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/BlikAlias","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CallbacksConfiguration","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardToken","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CertificatePinningConfiguration","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ExternallyGeneratedTransaction","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Notification","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payer","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PayerContext","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/RecursiveTransaction","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SingleTransaction"],"generated":true,"title":"Structures","anchor":"Structures"},{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/NotRegisteredBlikAlias","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/NotificationConfiguration","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/RegisteredBlikAlias"],"generated":true,"title":"Type Aliases","anchor":"Type-Aliases"},{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCard","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ConfigurationCheckResult","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/DigitalWallet","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Frequency","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Headless","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/InstallmentPayment","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Language","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/MerchantConfigurationError","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ModuleConfigurationError","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PayerContextConfigurationError","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentError","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentMethod","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Quantity","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Theme","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TransactionStatus"],"generated":true,"title":"Enumerations","anchor":"Enumerations"},{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SwiftUICore"],"generated":true,"title":"Extended Modules","anchor":"Extended-Modules"}],"references":{"doc://com.tpay.sdk/documentation/Tpay/AutomaticPayments":{"type":"topic","title":"Automatic payments","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments","abstract":[{"type":"text","text":"Providing automatic payment methods for a specific payer."}],"role":"article","kind":"article","url":"\/documentation\/tpay\/automaticpayments"},"doc://com.tpay.sdk/documentation/Tpay/TpayModule":{"navigatorTitle":[{"text":"TpayModule","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TpayModule","kind":"identifier"}],"url":"\/documentation\/tpay\/tpaymodule","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"TpayModule","type":"codeVoice"},{"type":"text","text":" encapsulates various functionalities for configuring and interacting with the Tpay payment module. It provides methods for setting up merchant details, payment methods, SSL certificates, language preferences, and more."}],"title":"TpayModule"},"doc://com.tpay.sdk/documentation/Tpay/Headless":{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Headless","title":"Headless","abstract":[{"text":"The ","type":"text"},{"code":"Headless","type":"codeVoice"},{"text":" API provides functionality for performing headless (without using Payment Sheet) transactions and handling payment-related operations. Developers can use this API to create and manage transactions independently, catering to specific use cases or custom user interfaces.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Headless","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Headless","kind":"identifier"}],"url":"\/documentation\/tpay\/headless"},"doc://com.tpay.sdk/documentation/Tpay/AliasRegistrationStatus":{"navigatorTitle":[{"text":"AliasRegistrationStatus","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AliasRegistrationStatus","kind":"identifier"}],"title":"AliasRegistrationStatus","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AliasRegistrationStatus","type":"topic","kind":"symbol","url":"\/documentation\/tpay\/aliasregistrationstatus"},"doc://com.tpay.sdk/documentation/Tpay/CallbacksConfiguration":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallbacksConfiguration"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CallbacksConfiguration","navigatorTitle":[{"kind":"identifier","text":"CallbacksConfiguration"}],"type":"topic","url":"\/documentation\/tpay\/callbacksconfiguration","title":"CallbacksConfiguration"},"doc://com.tpay.sdk/documentation/Tpay/SSLCertificatesProvider":{"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SSLCertificatesProvider"},{"type":"text","text":" protocol defines the properties required to provide SSL certificate-related configurations."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SSLCertificatesProvider","title":"SSLCertificatesProvider","url":"\/documentation\/tpay\/sslcertificatesprovider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SSLCertificatesProvider"}],"navigatorTitle":[{"kind":"identifier","text":"SSLCertificatesProvider"}]},"doc://com.tpay.sdk/documentation/Tpay/Changelog":{"abstract":[],"url":"\/documentation\/tpay\/changelog","title":"Changelog","type":"topic","role":"article","kind":"article","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Changelog"},"doc://com.tpay.sdk/documentation/Tpay/RegisteredBlikAlias":{"abstract":[{"text":"Represents an already registered BLIK alias in the system.","type":"text"}],"title":"RegisteredBlikAlias","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RegisteredBlikAlias"}],"url":"\/documentation\/tpay\/registeredblikalias","navigatorTitle":[{"kind":"identifier","text":"RegisteredBlikAlias"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/RegisteredBlikAlias"},"doc://com.tpay.sdk/documentation/Tpay/Installation":{"role":"article","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","abstract":[{"text":"How to install the SDK.","type":"text"}],"url":"\/documentation\/tpay\/installation","title":"Installation","type":"topic","kind":"article"},"doc://com.tpay.sdk/documentation/Tpay/BlikAlias":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BlikAlias"},{"type":"text","text":" struct represents a BLIK alias. It could serve wether as an alias to be registered during a regular BLIK payment, or as an already registered alias for a BLIK OneClick payment."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlikAlias"}],"title":"BlikAlias","url":"\/documentation\/tpay\/blikalias","navigatorTitle":[{"kind":"identifier","text":"BlikAlias"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/BlikAlias"},"doc://com.tpay.sdk/documentation/Tpay/CardToken":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardToken","kind":"identifier"}],"url":"\/documentation\/tpay\/cardtoken","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CardToken"},{"type":"text","text":" struct represents a tokenized card. It consists of a token’s body, a card tail and a card brand."}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardToken","role":"symbol","title":"CardToken","navigatorTitle":[{"text":"CardToken","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/PayerContextConfigurationError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PayerContextConfigurationError"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PayerContextConfigurationError"},{"type":"text","text":" enum represents specific errors related to payer context configuration settings."}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PayerContextConfigurationError","role":"symbol","title":"PayerContextConfigurationError","navigatorTitle":[{"kind":"identifier","text":"PayerContextConfigurationError"}],"kind":"symbol","type":"topic","url":"\/documentation\/tpay\/payercontextconfigurationerror"},"doc://com.tpay.sdk/documentation/Tpay/Payment":{"role":"collectionGroup","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","abstract":[{"text":"Creating and processing payment transactions.","type":"text"}],"url":"\/documentation\/tpay\/payment","title":"Payment","type":"topic","kind":"article"},"doc://com.tpay.sdk/documentation/Tpay/PaymentResult":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentResult","kind":"identifier"}],"abstract":[{"text":"A protocol representing the result of a payment operation.","type":"text"}],"type":"topic","title":"PaymentResult","role":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentResult","url":"\/documentation\/tpay\/paymentresult","navigatorTitle":[{"text":"PaymentResult","kind":"identifier"}],"kind":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/Transaction":{"role":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Transaction","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Transaction"}],"title":"Transaction","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Transaction"}],"url":"\/documentation\/tpay\/transaction"},"doc://com.tpay.sdk/documentation/Tpay":{"url":"\/documentation\/tpay","type":"topic","abstract":[],"title":"Tpay","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay","kind":"symbol","role":"collection"},"doc://com.tpay.sdk/documentation/Tpay/Recursive":{"abstract":[],"url":"\/documentation\/tpay\/recursive","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Recursive","type":"topic","role":"symbol","navigatorTitle":[{"text":"Recursive","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Recursive","kind":"identifier"}],"title":"Recursive"},"doc://com.tpay.sdk/documentation/Tpay/TransactionStatus":{"url":"\/documentation\/tpay\/transactionstatus","navigatorTitle":[{"text":"TransactionStatus","kind":"identifier"}],"title":"TransactionStatus","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransactionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TransactionStatus","abstract":[{"text":"The ","type":"text"},{"code":"TransactionStatus","type":"codeVoice"},{"text":" enum represents different statuses that a transaction can have.","type":"text"}],"type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/PayerContext":{"type":"topic","url":"\/documentation\/tpay\/payercontext","title":"PayerContext","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PayerContext","role":"symbol","navigatorTitle":[{"text":"PayerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PayerContext"},{"type":"text","text":" struct represents a context that combines information about a payer and their associated automatic payment methods."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PayerContext","kind":"identifier"}]},"doc://com.tpay.sdk/documentation/Tpay/TpayVersionString":{"title":"TpayVersionString","fragments":[{"kind":"identifier","text":"TpayVersionString"}],"type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayVersionString","abstract":[{"type":"text","text":"Project version string for Tpay."}],"url":"\/documentation\/tpay\/tpayversionstring","role":"symbol","kind":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/ExternallyGeneratedTransaction":{"title":"ExternallyGeneratedTransaction","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExternallyGeneratedTransaction"}],"type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ExternallyGeneratedTransaction","abstract":[{"type":"text","text":"A structure representing an externally generated transaction."}],"url":"\/documentation\/tpay\/externallygeneratedtransaction","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExternallyGeneratedTransaction"}]},"doc://com.tpay.sdk/documentation/Tpay/Frequency":{"type":"topic","url":"\/documentation\/tpay\/frequency","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Frequency"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Frequency","abstract":[],"kind":"symbol","title":"Frequency","navigatorTitle":[{"kind":"identifier","text":"Frequency"}]},"doc://com.tpay.sdk/documentation/Tpay/NotRegisteredBlikAlias":{"navigatorTitle":[{"text":"NotRegisteredBlikAlias","kind":"identifier"}],"url":"\/documentation\/tpay\/notregisteredblikalias","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/NotRegisteredBlikAlias","title":"NotRegisteredBlikAlias","role":"symbol","abstract":[{"type":"text","text":"Represents a BLIK alias to be registered during a standard BLIK transaction (payment via BLIK code)."}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotRegisteredBlikAlias","kind":"identifier"}]},"doc://com.tpay.sdk/documentation/Tpay/AddCardDelegate":{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCardDelegate","type":"topic","url":"\/documentation\/tpay\/addcarddelegate","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"AddCardDelegate","type":"codeVoice"},{"type":"text","text":" protocol defines the methods that a delegate should implement to handle events related to card tokenization."}],"title":"AddCardDelegate","navigatorTitle":[{"text":"AddCardDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddCardDelegate","kind":"identifier"}]},"doc://com.tpay.sdk/documentation/Tpay/InstallmentPayment":{"role":"symbol","navigatorTitle":[{"text":"InstallmentPayment","kind":"identifier"}],"url":"\/documentation\/tpay\/installmentpayment","type":"topic","title":"InstallmentPayment","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"InstallmentPayment"},{"type":"text","text":" enum represents various installment payment options available for use."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InstallmentPayment","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/InstallmentPayment","kind":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/Theme":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Theme","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Theme"},{"text":" enum defines different visual themes available for the Tpay module’s user interface. It includes cases for an automatic theme that follows system settings, as well as light and dark themes.","type":"text"}],"title":"Theme","url":"\/documentation\/tpay\/theme","navigatorTitle":[{"text":"Theme","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Theme","kind":"symbol","role":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/AutomaticPaymentMethods":{"navigatorTitle":[{"kind":"identifier","text":"AutomaticPaymentMethods"}],"kind":"symbol","title":"AutomaticPaymentMethods","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomaticPaymentMethods"}],"abstract":[{"type":"text","text":"The "},{"code":"AutomaticPaymentMethods","type":"codeVoice"},{"type":"text","text":" struct represents a collection of automatic payment methods associated with a concrete payer."}],"type":"topic","url":"\/documentation\/tpay\/automaticpaymentmethods","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPaymentMethods"},"doc://com.tpay.sdk/documentation/Tpay/VersionSupport":{"title":"Version support","type":"topic","abstract":[{"text":"TBD","type":"text"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/VersionSupport","url":"\/documentation\/tpay\/versionsupport","kind":"article","role":"article"},"doc://com.tpay.sdk/documentation/Tpay/PaymentError":{"url":"\/documentation\/tpay\/paymenterror","title":"PaymentError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentError","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentError","type":"topic","navigatorTitle":[{"text":"PaymentError","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"PaymentError"},{"text":" enum encompasses various errors related to payment processes.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Quantity":{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Quantity","url":"\/documentation\/tpay\/quantity","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Quantity","kind":"identifier"}],"title":"Quantity","role":"symbol","navigatorTitle":[{"text":"Quantity","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/TransactionStatusObserver":{"url":"\/documentation\/tpay\/transactionstatusobserver","abstract":[{"text":"The ","type":"text"},{"code":"TransactionStatusObserver","type":"codeVoice"},{"text":" protocol defines a method that an observer should implement to receive updates about transaction statuses.","type":"text"}],"title":"TransactionStatusObserver","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransactionStatusObserver","kind":"identifier"}],"navigatorTitle":[{"text":"TransactionStatusObserver","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TransactionStatusObserver","type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/Permissions":{"url":"\/documentation\/tpay\/permissions","type":"topic","abstract":[{"text":"Required app permissions.","type":"text"}],"title":"Permissions","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions","role":"article","kind":"article"},"doc://com.tpay.sdk/documentation/Tpay/Address":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Address"}],"role":"symbol","url":"\/documentation\/tpay\/address","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Address"}],"title":"Address","abstract":[],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Address"},"doc://com.tpay.sdk/documentation/Tpay/ModuleError":{"kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ModuleError","url":"\/documentation\/tpay\/moduleerror","abstract":[],"title":"ModuleError","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleError"}],"navigatorTitle":[{"kind":"identifier","text":"ModuleError"}]},"doc://com.tpay.sdk/documentation/Tpay/CertificatePinningConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CertificatePinningConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CertificatePinningConfiguration","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"CertificatePinningConfiguration"},{"text":" struct represents a configuration for certificate pinning, a security mechanism that ensures secure communication between an app and a server by verifying the server’s certificate against pre-defined public key hashes.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CertificatePinningConfiguration","title":"CertificatePinningConfiguration","type":"topic","url":"\/documentation\/tpay\/certificatepinningconfiguration"},"doc://com.tpay.sdk/documentation/Tpay/RecursiveTransaction":{"abstract":[{"type":"text","text":"The "},{"code":"RecursiveTransaction","type":"codeVoice"},{"type":"text","text":" struct represents a recursive transaction. It extends a specified transaction object with recursion parameters such as the frequency, quantity, and expiry date."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecursiveTransaction","kind":"identifier"}],"kind":"symbol","title":"RecursiveTransaction","url":"\/documentation\/tpay\/recursivetransaction","type":"topic","navigatorTitle":[{"text":"RecursiveTransaction","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/RecursiveTransaction"},"doc://com.tpay.sdk/documentation/Tpay/SwiftUICore":{"kind":"symbol","type":"topic","url":"\/documentation\/tpay\/swiftuicore","title":"SwiftUICore","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SwiftUICore","abstract":[],"role":"collection"},"doc://com.tpay.sdk/documentation/Tpay/CardTokenization":{"url":"\/documentation\/tpay\/cardtokenization","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","abstract":[{"type":"text","text":"Saving credit card details for future purchases."}],"role":"collectionGroup","type":"topic","title":"Card tokenization","kind":"article"},"doc://com.tpay.sdk/documentation/Tpay/Language":{"navigatorTitle":[{"text":"Language","kind":"identifier"}],"title":"Language","abstract":[{"type":"text","text":"The "},{"code":"Language","type":"codeVoice"},{"type":"text","text":" enum represents different language options using their respective language codes."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Language","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Language","kind":"identifier"}],"url":"\/documentation\/tpay\/language"},"doc://com.tpay.sdk/documentation/Tpay/MerchantConfigurationError":{"url":"\/documentation\/tpay\/merchantconfigurationerror","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MerchantConfigurationError"}],"kind":"symbol","title":"MerchantConfigurationError","abstract":[{"text":"The ","type":"text"},{"code":"MerchantConfigurationError","type":"codeVoice"},{"text":" enum represents various errors related to merchant configuration settings.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MerchantConfigurationError"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/MerchantConfigurationError","type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/ConfigurationCheckResult":{"type":"topic","title":"ConfigurationCheckResult","navigatorTitle":[{"kind":"identifier","text":"ConfigurationCheckResult"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ConfigurationCheckResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurationCheckResult"}],"role":"symbol","url":"\/documentation\/tpay\/configurationcheckresult","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ConfigurationCheckResult"},{"type":"text","text":" enum represents the outcome of a configuration check, indicating whether the configuration is valid or invalid, along with relevant error information."}]},"doc://com.tpay.sdk/documentation/Tpay/MerchantDetailsProvider":{"type":"topic","abstract":[{"text":"A type that provides merchant-specific information displayed across module screens.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MerchantDetailsProvider","kind":"identifier"}],"url":"\/documentation\/tpay\/merchantdetailsprovider","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/MerchantDetailsProvider","kind":"symbol","title":"MerchantDetailsProvider","navigatorTitle":[{"text":"MerchantDetailsProvider","kind":"identifier"}]},"doc://com.tpay.sdk/documentation/Tpay/AddCard":{"navigatorTitle":[{"text":"AddCard","kind":"identifier"}],"title":"AddCard","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCard","url":"\/documentation\/tpay\/addcard","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddCard","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://com.tpay.sdk/documentation/Tpay/Merchant":{"abstract":[{"text":"The ","type":"text"},{"code":"Merchant","type":"codeVoice"},{"text":" struct represents a merchant’s configuration for interacting with payment services. This configuration includes various settings such as authorization details, card processing settings, environment type, BLIK payment settings, and wallet integration settings.","type":"text"}],"kind":"symbol","type":"topic","title":"Merchant","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant","url":"\/documentation\/tpay\/merchant","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Merchant"}],"navigatorTitle":[{"kind":"identifier","text":"Merchant"}]},"doc://com.tpay.sdk/documentation/Tpay/Button":{"title":"Button","role":"symbol","fragments":[{"text":"Button","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Button","type":"topic","kind":"symbol","url":"\/documentation\/tpay\/button","abstract":[{"text":"The specialized UIButton designed to serve as an effortless entry point for invoking the payment sheet within your app.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/WebViewPaymentDelegate":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WebViewPaymentDelegate"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"WebViewPaymentDelegate"},{"type":"text","text":" protocol defines the methods that a delegate should implement to handle web view payment-related events."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewPaymentDelegate"}],"title":"WebViewPaymentDelegate","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/WebViewPaymentDelegate","url":"\/documentation\/tpay\/webviewpaymentdelegate"},"doc://com.tpay.sdk/documentation/Tpay/NotificationConfiguration":{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/NotificationConfiguration","url":"\/documentation\/tpay\/notificationconfiguration","abstract":[{"type":"text","text":"Typealias for React Native (fix for issue with colliding Notification and Foundation.Notification)"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NotificationConfiguration"}],"title":"NotificationConfiguration","type":"topic","role":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/PaymentMethod":{"navigatorTitle":[{"text":"PaymentMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PaymentMethod"},{"type":"text","text":" enum represents various payment methods available for transactions."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentMethod","kind":"identifier"}],"url":"\/documentation\/tpay\/paymentmethod","type":"topic","title":"PaymentMethod","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentMethod","role":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/Payer":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Payer","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"Payer","type":"codeVoice"},{"text":" struct represents information about a payer, such as a customer or an account holder. This information includes the payer’s name, email, phone number, and address.","type":"text"}],"title":"Payer","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payer","url":"\/documentation\/tpay\/payer","navigatorTitle":[{"text":"Payer","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/SingleTransaction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleTransaction"}],"url":"\/documentation\/tpay\/singletransaction","title":"SingleTransaction","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SingleTransaction","abstract":[{"type":"text","text":"The "},{"code":"SingleTransaction","type":"codeVoice"},{"type":"text","text":" struct represents a single transaction with associated properties such as the transaction amount, description, and payer context."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SingleTransaction"}],"type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/DigitalWallet":{"role":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/DigitalWallet","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DigitalWallet"},{"type":"text","text":" enum represents various digital wallet options available for use."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalWallet","kind":"identifier"}],"navigatorTitle":[{"text":"DigitalWallet","kind":"identifier"}],"title":"DigitalWallet","url":"\/documentation\/tpay\/digitalwallet","type":"topic","kind":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/ModuleConfigurationError":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleConfigurationError"}],"title":"ModuleConfigurationError","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/ModuleConfigurationError","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ModuleConfigurationError"},{"type":"text","text":" enum encompasses different errors related to module configuration settings."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModuleConfigurationError"}],"url":"\/documentation\/tpay\/moduleconfigurationerror","kind":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/Basics":{"title":"Basics","type":"topic","kind":"article","abstract":[{"text":"How to start.","type":"text"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics","role":"article","url":"\/documentation\/tpay\/basics"},"doc://com.tpay.sdk/documentation/Tpay/TpayVersionNumber":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayVersionNumber","abstract":[{"text":"Project version number for Tpay.","type":"text"}],"fragments":[{"text":"TpayVersionNumber","kind":"identifier"}],"title":"TpayVersionNumber","url":"\/documentation\/tpay\/tpayversionnumber","role":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/Notification":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Notification"}],"title":"Notification","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Notification","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Notification"}],"url":"\/documentation\/tpay\/notification","abstract":[{"type":"text","text":"Configuration for transaction notification"}]},"doc://com.tpay.sdk/documentation/Tpay/PaymentDelegate":{"title":"PaymentDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentDelegate","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PaymentDelegate"},{"type":"text","text":" protocol defines the methods that a delegate should implement to handle payment-related events."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PaymentDelegate","kind":"identifier"}],"url":"\/documentation\/tpay\/paymentdelegate"},"doc://com.tpay.sdk/documentation/Tpay/Presentable":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/tpay\/presentable","abstract":[],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Presentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presentable"}],"title":"Presentable","navigatorTitle":[{"kind":"identifier","text":"Presentable"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Getting-started","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics"],"title":"Getting started"},{"anchor":"Use-cases","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments"],"title":"Use cases"},{"generated":true,"anchor":"Articles","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Changelog","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/VersionSupport"],"title":"Articles"},{"generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Button"],"title":"Classes"},{"generated":true,"anchor":"Variables","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayVersionNumber","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayVersionString"],"title":"Variables"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}