options:
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
    - Type
    - Subject
  commits:
    filters:
      Type:
      - feat
      - fix
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
  notes:
    keywords:
    - BREAKING CHANGE