{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tpay\/automaticpayments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tpay\/automaticpayments"]}],"hierarchy":{"paths":[["doc:\/\/com.tpay.sdk\/documentation\/Tpay"]]},"identifier":{"url":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments","interfaceLanguage":"swift"},"kind":"article","metadata":{"title":"Automatic payments","roleHeading":"Article","role":"article","modules":[{"name":"Tpay"}]},"abstract":[{"type":"text","text":"Providing automatic payment methods for a specific payer."}],"seeAlsoSections":[{"title":"Use cases","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization"],"generated":true,"anchor":"Use-cases"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"content":[{"type":"heading","anchor":"Card-OneClick-payment","text":"Card OneClick payment","level":2},{"type":"paragraph","inlineContent":[{"text":"The Tpay module gives the user the ability to store credit card details that users can reuse for future payments without the need to re-enter their information.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The payer has the option to save their credit card information either while making a purchase within the payment flow (","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","type":"reference"},{"text":") or through a dedicated ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","type":"reference"},{"text":" process.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"In order to support this feature, please follow ","type":"text"},{"type":"codeVoice","code":"Notifications And Receiving Data After Transaction"},{"text":" section under ","type":"text"},{"isActive":true,"identifier":"https:\/\/openapi.tpay.com","type":"reference"},{"text":".","type":"text"}]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This section assumes your app is already in possesion of a payer’s card tokens and associated details."}]}],"name":"Note"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For each payer’s tokenized card, create "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardToken"},{"type":"text","text":" instance and pass them with the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PayerContext"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["let card = CardToken(token: token, cardTail: tail, brand: brand)","let payerContext = PayerContext(payer: payer,","                                automaticPaymentMethods: .init(tokenizedCards: [card]))"]},{"type":"heading","anchor":"BLIK-OneClick-payment","text":"BLIK OneClick payment","level":2},{"type":"paragraph","inlineContent":[{"text":"To enable BLIK OneClick functionality for users, the first step is to define an alias that will be registered within the BLIK ecosystem when a user is willing to do so.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can provide one when configuring your "},{"code":"Merchant","type":"codeVoice"},{"type":"text","text":" using "},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/BlikConfiguration","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["let blikConfiguration = Merchant.BlikConfiguration(aliasToBeRegistered: .init(value: .uid(\"myBlikAlias\")))","let merchant = Merchant(authorization: authorization, blikConfiguration: blikConfiguration)"]},{"type":"paragraph","inlineContent":[{"text":"After receiving a notification about alias registration event (described in ","type":"text"},{"code":"Notifications And Receiving Data After Transaction","type":"codeVoice"},{"text":" section under ","type":"text"},{"identifier":"https:\/\/openapi.tpay.com","overridingTitleInlineContent":[{"type":"text","text":"OpenAPI documentation"}],"isActive":true,"overridingTitle":"OpenAPI documentation","type":"reference"},{"text":"), you can pass it along with the ","type":"text"},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PayerContext","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This section assumes your app is already in possesion of a payer’s registered alias."}]}],"name":"Note"},{"type":"codeListing","syntax":"swift","code":["let blikAlias = RegisteredBlikAlias(value: .uid(retrievedAlias))","let payerContext = PayerContext(payer: payer,","                                automaticPaymentMethods: .init(registeredBlikAlias: blikAlias))"]}],"kind":"content"}],"sections":[],"references":{"doc://com.tpay.sdk/documentation/Tpay/Payment":{"role":"collectionGroup","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","abstract":[{"text":"Creating and processing payment transactions.","type":"text"}],"url":"\/documentation\/tpay\/payment","title":"Payment","type":"topic","kind":"article"},"doc://com.tpay.sdk/documentation/Tpay/CardToken":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardToken","kind":"identifier"}],"url":"\/documentation\/tpay\/cardtoken","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CardToken"},{"type":"text","text":" struct represents a tokenized card. It consists of a token’s body, a card tail and a card brand."}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardToken","role":"symbol","title":"CardToken","navigatorTitle":[{"text":"CardToken","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/PayerContext":{"type":"topic","url":"\/documentation\/tpay\/payercontext","title":"PayerContext","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PayerContext","role":"symbol","navigatorTitle":[{"text":"PayerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PayerContext"},{"type":"text","text":" struct represents a context that combines information about a payer and their associated automatic payment methods."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PayerContext","kind":"identifier"}]},"https://openapi.tpay.com":{"type":"link","url":"https:\/\/openapi.tpay.com","identifier":"https:\/\/openapi.tpay.com","title":"OpenAPI documentation","titleInlineContent":[{"type":"text","text":"OpenAPI documentation"}]},"doc://com.tpay.sdk/documentation/Tpay/CardTokenization":{"url":"\/documentation\/tpay\/cardtokenization","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","abstract":[{"type":"text","text":"Saving credit card details for future purchases."}],"role":"collectionGroup","type":"topic","title":"Card tokenization","kind":"article"},"doc://com.tpay.sdk/documentation/Tpay/Merchant/BlikConfiguration":{"navigatorTitle":[{"text":"BlikConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/tpay\/merchant\/blikconfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BlikConfiguration","kind":"identifier"}],"title":"Merchant.BlikConfiguration","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/BlikConfiguration","role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BlikConfiguration"},{"type":"text","text":" struct encompasses configuration settings related to BLIK payments, including the option to specify a BLIK alias to be registered during a standard BLIK transaction to allow a payer to perform BLIK OneClick payments during future transactions."}]},"doc://com.tpay.sdk/documentation/Tpay":{"url":"\/documentation\/tpay","type":"topic","abstract":[],"title":"Tpay","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"title":"Use cases","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization"],"generated":true,"anchor":"Use-cases"}],"path":"\/seeAlsoSections","op":"replace"}]}]}