{"metadata":{"modules":[{"name":"Tpay"}],"role":"article","title":"Basics","roleHeading":"Article"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.tpay.sdk\/documentation\/Tpay"]]},"seeAlsoSections":[{"title":"Getting started","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions"],"generated":true,"anchor":"Getting-started"}],"identifier":{"url":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics","interfaceLanguage":"swift"},"kind":"article","variants":[{"paths":["\/documentation\/tpay\/basics"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tpay\/basics"]}],"abstract":[{"text":"How to start.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"text":"To start using the Tpay SDK, you’ll primarily interact with the methods provided by the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule"},{"text":" API. This API encapsulates essential configuration steps, transaction management, and further interaction with the Tpay payment ecosystem.","type":"text"}],"type":"paragraph"},{"name":"Note","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"There is no need for Module\/Marchant setup when dealing with WebView integration.","type":"text"}],"type":"paragraph"}],"style":"note","type":"aside"},{"anchor":"Merchant-configuration","level":2,"text":"Merchant configuration","type":"heading"},{"inlineContent":[{"text":"Configuring a merchant is an essential step when integrating the Tpay SDK into your app. A merchant configuration provides the necessary details for processing payments and establishing a connection with Tpay’s payment ecosystem.","type":"text"}],"type":"paragraph"},{"anchor":"Authorization-details","level":3,"text":"Authorization details","type":"heading"},{"inlineContent":[{"text":"Collect the merchant’s authorization details, such as the ","type":"text"},{"code":"clientId","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":". You can create an instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/Authorization"},{"text":" with these details:","type":"text"}],"type":"paragraph"},{"code":["let authorization = Merchant.Authorization(clientId: \"your_client_id\", clientSecret: \"your_client_secret\")"],"syntax":"swift","type":"codeListing"},{"anchor":"Merchant","level":3,"text":"Merchant","type":"heading"},{"inlineContent":[{"text":"Now, create a ","type":"text"},{"code":"Merchant","type":"codeVoice"},{"text":" instance by combining the ","type":"text"},{"code":"authorization","type":"codeVoice"},{"text":" with other optional configurations such as ","type":"text"},{"code":"cardsConfiguration","type":"codeVoice"},{"text":", ","type":"text"},{"code":"blikConfiguration","type":"codeVoice"},{"text":", and more. Here’s an example of creating a basic ","type":"text"},{"code":"Merchant","type":"codeVoice"},{"text":" configuration:","type":"text"}],"type":"paragraph"},{"code":["let merchant = Merchant(authorization: authorization)"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"You can customize the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant"},{"text":" instance further based on your app’s requirements.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(merchant:)"},{"text":" method to set up the merchant configuration within the Tpay SDK:","type":"text"}],"type":"paragraph"},{"code":["do {","    try TpayModule.configure(merchant: merchant)","    \/\/ Configuration successful","} catch {","    \/\/ Handle configuration errors","}"],"syntax":"swift","type":"codeListing"},{"anchor":"Merchant-details","level":3,"text":"Merchant details","type":"heading"},{"inlineContent":[{"text":"Create a type conforming to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/MerchantDetailsProvider"},{"text":" protocol by implementing its required methods. Provide localized versions for each part of the information. This strings will appear on the Tpay module screens and are required to satisfy GDPR requirements. For example:","type":"text"}],"type":"paragraph"},{"code":["class MyMerchantDetailsProvider: MerchantDetailsProvider {","    func merchantDisplayName(for language: Language) -> String {","        \/\/ Return the merchant's display name based on the specified language","    }","    ","    func merchantHeadquarters(for language: Language) -> String? {","        \/\/ Return the merchant's headquarters location based on the specified language","    }","    ","    func regulationsLink(for language: Language) -> URL {","        \/\/ Return the URL to the regulations page based on the specified language","    }","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"Use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(merchantDetailsProvider:)"},{"text":" method to set up the merchant details provider:","type":"text"}],"type":"paragraph"},{"code":["TpayModule.configure(merchantDetailsProvider: myMerchantDetailsProvider)"],"syntax":"swift","type":"codeListing"},{"anchor":"Available-payment-methods","level":3,"text":"Available payment methods","type":"heading"},{"inlineContent":[{"text":"The Tpay SDK supports a range of payment methods, including credit cards, BLIK, digital wallets, and more. By configuring the available payment methods, you can control which options are presented to users during the payment process.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Create an array of desired payment methods you want to offer to users:","type":"text"}],"type":"paragraph"},{"code":["let paymentMethods: [PaymentMethod] = [.card, .blik, .digitalWallet(.applePay)]"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"Use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(paymentMethods:)"},{"text":" method to set up the available payment methods:","type":"text"}],"type":"paragraph"},{"code":["do {","    try TpayModule.configure(paymentMethods: paymentMethods)","    \/\/ Configuration successful","} catch {","    \/\/ Handle configuration errors","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"If not specified, module will present all payment methods by default.","type":"text"}],"type":"paragraph"},{"name":"Important","content":[{"inlineContent":[{"text":"Some payment methods may require additional setup to make them run succesfully.","type":"text"},{"text":" ","type":"text"},{"text":"See: ","type":"text"},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/CardsAPI","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/WalletConfiguration\/ApplePayConfiguration","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"style":"important","type":"aside"},{"anchor":"Languages-support","level":3,"text":"Languages support","type":"heading"},{"inlineContent":[{"text":"Use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(preferredLanguage:supportedLanguages:)"},{"text":" method to set up the language preferences:","type":"text"}],"type":"paragraph"},{"code":["do {","    try TpayModule.configure(preferredLanguage: .en, supportedLanguages: .allCases)","    \/\/ Configuration successful","} catch {","    \/\/ Handle configuration errors","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"If not specified, module will support all implemented languages (see: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Language"},{"text":") and will start in ","type":"text"},{"code":".pl","type":"codeVoice"},{"text":" language by default.","type":"text"}],"type":"paragraph"},{"anchor":"Security-SSL-pinning","level":3,"text":"Security (SSL pinning)","type":"heading"},{"inlineContent":[{"text":"The Tpay SDK’s ","type":"text"},{"code":"TpayModule","type":"codeVoice"},{"text":" offers the capability to enhance the security of your app’s communication with Tpay’s servers by implementing SSL pinning. SSL pinning is a security technique that ensures your app only communicates with servers that possess specific SSL certificates, guarding against potential security vulnerabilities.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"SSL pinning involves comparing a server’s SSL certificate with a pre-defined certificate or a set of trusted certificates. By configuring SSL pinning via the ","type":"text"},{"code":"TpayModule","type":"codeVoice"},{"text":", you strengthen the security of the connection between your app and Tpay’s servers, reducing the risk of data interception or tampering.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"In order to configure SSL pinning, create a type conforming to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SSLCertificatesProvider"},{"text":" protocol by implementing its required methods and pass it via ","type":"text"},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(sslCertificatesProvider:)","isActive":true,"type":"reference"},{"type":"text","text":" method:"}],"type":"paragraph"},{"code":["TpayModule.configure(sslCertificatesProvider: sslProvider)"],"syntax":"swift","type":"codeListing"},{"anchor":"Setup-validation","level":3,"text":"Setup validation","type":"heading"},{"inlineContent":[{"text":"The ","type":"text"},{"code":"TpayModule","type":"codeVoice"},{"text":" provides a convenient method to check the overall configuration of your app’s payment settings. The configuration check method helps ensure that all required parameters and settings are properly configured before initiating payment processes, reducing the likelihood of errors and providing a smoother user experience.","type":"text"}],"type":"paragraph"},{"code":["do {","    try TpayModule.configure(merchant: merchant)","        .configure(paymentMethods: paymentMethods)","        .configure(sslCertificatesProvider: sslProvider)","        .configure(merchantDetailsProvider: detailsProvider)","        .configure(preferredLanguage: .en, supportedLanguages: [.en, .pl])","    \/\/ Configuration chain completed successfully","} catch {","    \/\/ Handle configuration errors","}","","let configurationCheckResult = TpayModule.checkConfiguration()","","switch configurationCheckResult {","case .valid:","    \/\/ Configuration is complete and valid, proceed with payment processes","case .invalid(let error):","    \/\/ Configuration is invalid, handle the specific error accordingly","}"],"syntax":"swift","type":"codeListing"},{"name":"Tip","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"You can chain multiple configuration methods."}],"type":"paragraph"}],"style":"tip","type":"aside"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Now you are ready to start using main Tpay module features: "},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","type":"reference","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Note"}]}],"references":{"doc://com.tpay.sdk/documentation/Tpay/TpayModule/configure(paymentMethods:)":{"url":"\/documentation\/tpay\/tpaymodule\/configure(paymentmethods:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(paymentMethods:)","title":"configure(paymentMethods:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay13PaymentMethodO","text":"PaymentMethod"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"TpayModule","preciseIdentifier":"s:4Tpay0A6ModuleO"},{"kind":"text","text":".Type"}],"abstract":[{"text":"Configures the Tpay module with supported payment methods.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Merchant/Authorization":{"url":"\/documentation\/tpay\/merchant\/authorization","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/Authorization","navigatorTitle":[{"kind":"identifier","text":"Authorization"}],"title":"Merchant.Authorization","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Authorization"}],"abstract":[{"text":"The ","type":"text"},{"code":"Authorization","type":"codeVoice"},{"text":" struct represents the authorization details required for secure interactions with payment services.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/TpayModule/configure(merchantDetailsProvider:)":{"url":"\/documentation\/tpay\/tpaymodule\/configure(merchantdetailsprovider:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(merchantDetailsProvider:)","title":"configure(merchantDetailsProvider:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"merchantDetailsProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay23MerchantDetailsProviderP","text":"MerchantDetailsProvider"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay0A6ModuleO","text":"TpayModule"},{"kind":"text","text":".Type"}],"abstract":[{"text":"Configures the Tpay module with merchant details provider.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Merchant/WalletConfiguration/ApplePayConfiguration":{"url":"\/documentation\/tpay\/merchant\/walletconfiguration\/applepayconfiguration","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/WalletConfiguration\/ApplePayConfiguration","navigatorTitle":[{"kind":"identifier","text":"ApplePayConfiguration"}],"title":"Merchant.WalletConfiguration.ApplePayConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePayConfiguration"}],"abstract":[{"text":"The ","type":"text"},{"code":"ApplePayConfiguration","type":"codeVoice"},{"text":" struct encapsulates essential configuration settings for integrating Apple Pay.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/TpayModule":{"url":"\/documentation\/tpay\/tpaymodule","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule","navigatorTitle":[{"kind":"identifier","text":"TpayModule"}],"title":"TpayModule","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TpayModule"}],"abstract":[{"text":"The ","type":"text"},{"code":"TpayModule","type":"codeVoice"},{"text":" encapsulates various functionalities for configuring and interacting with the Tpay payment module. It provides methods for setting up merchant details, payment methods, SSL certificates, language preferences, and more.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/SSLCertificatesProvider":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SSLCertificatesProvider"}],"title":"SSLCertificatesProvider","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SSLCertificatesProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SSLCertificatesProvider"}],"url":"\/documentation\/tpay\/sslcertificatesprovider","abstract":[{"type":"text","text":"The "},{"code":"SSLCertificatesProvider","type":"codeVoice"},{"type":"text","text":" protocol defines the properties required to provide SSL certificate-related configurations."}]},"doc://com.tpay.sdk/documentation/Tpay/Language":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Language"}],"title":"Language","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Language","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Language"}],"url":"\/documentation\/tpay\/language","abstract":[{"type":"text","text":"The "},{"code":"Language","type":"codeVoice"},{"type":"text","text":" enum represents different language options using their respective language codes."}]},"doc://com.tpay.sdk/documentation/Tpay/CardTokenization":{"url":"\/documentation\/tpay\/cardtokenization","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","title":"Card tokenization","abstract":[{"text":"Saving credit card details for future purchases.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Merchant":{"url":"\/documentation\/tpay\/merchant","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant","navigatorTitle":[{"kind":"identifier","text":"Merchant"}],"title":"Merchant","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Merchant"}],"abstract":[{"text":"The ","type":"text"},{"code":"Merchant","type":"codeVoice"},{"text":" struct represents a merchant’s configuration for interacting with payment services. This configuration includes various settings such as authorization details, card processing settings, environment type, BLIK payment settings, and wallet integration settings.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Installation":{"role":"article","title":"Installation","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","kind":"article","url":"\/documentation\/tpay\/installation","abstract":[{"text":"How to install the SDK.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay":{"role":"collection","title":"Tpay","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay","kind":"symbol","url":"\/documentation\/tpay","abstract":[]},"doc://com.tpay.sdk/documentation/Tpay/MerchantDetailsProvider":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MerchantDetailsProvider"}],"title":"MerchantDetailsProvider","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/MerchantDetailsProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MerchantDetailsProvider"}],"url":"\/documentation\/tpay\/merchantdetailsprovider","abstract":[{"type":"text","text":"A type that provides merchant-specific information displayed across module screens."}]},"doc://com.tpay.sdk/documentation/Tpay/Merchant/CardsAPI":{"url":"\/documentation\/tpay\/merchant\/cardsapi","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Merchant\/CardsAPI","navigatorTitle":[{"kind":"identifier","text":"CardsAPI"}],"title":"Merchant.CardsAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardsAPI"}],"abstract":[{"text":"The ","type":"text"},{"code":"CardsAPI","type":"codeVoice"},{"text":" struct encapsulates the configuration for interacting with card-related APIs, including the public key required for encrypting sensitive credit card data during communication.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/TpayModule/configure(sslCertificatesProvider:)":{"url":"\/documentation\/tpay\/tpaymodule\/configure(sslcertificatesprovider:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(sslCertificatesProvider:)","title":"configure(sslCertificatesProvider:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sslCertificatesProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay23SSLCertificatesProviderP","text":"SSLCertificatesProvider"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay0A6ModuleO","text":"TpayModule"},{"kind":"text","text":".Type"}],"abstract":[{"text":"Configures the Tpay module with SSL certificate information.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Permissions":{"role":"article","title":"Permissions","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions","kind":"article","url":"\/documentation\/tpay\/permissions","abstract":[{"text":"Required app permissions.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/TpayModule/configure(merchant:)":{"url":"\/documentation\/tpay\/tpaymodule\/configure(merchant:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(merchant:)","title":"configure(merchant:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"merchant"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay8MerchantV","text":"Merchant"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay0A6ModuleO","text":"TpayModule"},{"text":".Type","kind":"text"}],"abstract":[{"text":"Configures the Tpay module with merchant details.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/TpayModule/configure(preferredLanguage:supportedLanguages:)":{"url":"\/documentation\/tpay\/tpaymodule\/configure(preferredlanguage:supportedlanguages:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/TpayModule\/configure(preferredLanguage:supportedLanguages:)","title":"configure(preferredLanguage:supportedLanguages:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"preferredLanguage"},{"text":": ","kind":"text"},{"text":"Language","kind":"typeIdentifier","preciseIdentifier":"s:4Tpay8LanguageO"},{"text":", ","kind":"text"},{"text":"supportedLanguages","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay8LanguageO","text":"Language"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:4Tpay0A6ModuleO","text":"TpayModule"},{"kind":"text","text":".Type"}],"abstract":[{"text":"Configures the Tpay module with preferred and supported languages.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Payment":{"url":"\/documentation\/tpay\/payment","role":"article","type":"topic","kind":"article","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","title":"Payment","abstract":[{"text":"Creating and processing payment transactions.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Getting-started","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions"],"generated":true,"title":"Getting started"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}