{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The Tpay SDK provides a way to register a credit card without performing a payment transaction, so a users can define their cards for future OneClick payments.","type":"text"}]},{"anchor":"AddCard-sheet","type":"heading","level":2,"text":"AddCard sheet"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCard\/Sheet","type":"reference","isActive":true},{"text":" is designed to guide the user through the card tokenization process. Sheet is presented in a modal style, providing a focused and intuitive interaction. The class interacts with the provided ","type":"text"},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCardDelegate","type":"reference","isActive":true},{"text":" to notify about tokenization events.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"To create an instance of the ","type":"text"},{"code":"Sheet","type":"codeVoice"},{"text":" class, initialize it with a ","type":"text"},{"code":"Payer","type":"codeVoice"},{"text":" object and an optional ","type":"text"},{"code":"AddCardDelegate","type":"codeVoice"},{"text":":","type":"text"}]},{"code":["let addCardSheet = AddCard.Sheet(payer: payer, delegate: delegate)"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Use the ","type":"text"},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCard\/Sheet\/present(from:)","type":"reference","isActive":true},{"text":" method to present the sheet from a view controller:","type":"text"}]},{"code":["do {","    try addCardSheet.present(from: presentingViewController)","} catch {","    \/\/ Handle configuration errors or other exceptions","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"To dismiss the sheet manually, call the ","type":"text"},{"code":"dismiss()","type":"codeVoice"},{"text":" method:","type":"text"}]},{"code":["addCardSheet.dismiss()"],"type":"codeListing","syntax":"swift"},{"anchor":"SwiftUI-way","type":"heading","level":3,"text":"SwiftUI way"},{"code":["struct ContentView: View {","    @State private var isTokenizationSheetPresented = false","","    var body: some View {","        Button(\"Add Card\") {","            isTokenizationSheetPresented.toggle()","        }","        .presentCardTokenizationSheet(isPresented: $isTokenizationSheetPresented) {","            \/\/ Handle card tokenization completed","        } onTokenizationCancelled: {","            \/\/ Handle card tokenization cancelled","        } onErrorOccured: { error in","            \/\/ Handle tokenization error","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"anchor":"Headless-Payment","type":"heading","level":2,"text":"Headless Payment"},{"type":"paragraph","inlineContent":[{"text":"Tpay SDK allows you to make payment without any predefined screen.","type":"text"},{"text":" ","type":"text"},{"text":"To do so use ","type":"text"},{"code":"Tpay.Headless.Models.Card","type":"codeVoice"},{"text":" class.","type":"text"}]},{"code":["do {","    try Headless.invokePayment(","        for: SingleTransaction(","            amount: 250,","            description: \"test\",","            hiddenDescription: \"hidden message\",","            payerContext: PayerContext(","                payer: Payer(","                    name: \"Test\",","                    email: \"email@address.com\",","                ),","            ),","        ),","        using: chosenPaymentChannel,","        with: Tpay.Headless.Models.Card(","            number: \"4056 2178 4359 7258\",","            expiryDate: Headless.Models.Card.ExpiryDate(month: 12, year: 35),","            securityCode: \"123\",","            shouldTokenize: false,","        )","    ) { result in","        switch result {","        case .success(let paymentResult):","            \/\/ Handle payment result","        case .failure(let error):","            \/\/ Handle payment error","        }","    }","} catch {","    \/\/ Handle invocation errors or other exceptions","}"],"type":"codeListing","syntax":"swift"},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"[!Warning]"},{"type":"text","text":" "},{"type":"text","text":"If "},{"code":"paymentResult","type":"codeVoice"},{"type":"text","text":" returns "},{"code":"continueUrl","type":"codeVoice"},{"type":"text","text":", you have to handle it"},{"type":"text","text":" "},{"type":"text","text":"and redirect user to it in order to complete the payment."}],"type":"paragraph"}]},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"[!Warning]"},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"paymentResult"},{"type":"text","text":" returns "},{"type":"codeVoice","code":"paid"},{"type":"text","text":" in "},{"type":"codeVoice","code":"status"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"it means that transaction has been paid automatically during creation."}],"type":"paragraph"}],"type":"aside","style":"note"},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"[!Warning]"},{"type":"text","text":" "},{"type":"text","text":"Generated card token will be sent to "},{"code":"notificationUrl","type":"codeVoice"},{"type":"text","text":" specified in the notifications callbacks."}],"type":"paragraph"}]},{"anchor":"Tokenization","level":4,"type":"heading","text":"Tokenization"},{"type":"paragraph","inlineContent":[{"text":"You can also Opt-in to generate a credit card token for future payments","type":"text"},{"text":" ","type":"text"},{"text":"if you want to let users pay for transactions with previously used card.","type":"text"},{"text":" ","type":"text"},{"text":"To do so, in ","type":"text"},{"code":"Tpay.Headless.Models.Card","type":"codeVoice"},{"text":" class, set the ","type":"text"},{"code":"shouldTokenize","type":"codeVoice"},{"text":" to true.","type":"text"}]},{"code":["with: Tpay.Headless.Models.Card(","    number: \"4056 2178 4359 7258\",","    expiryDate: Headless.Models.Card.ExpiryDate(month: 12, year: 35),","    securityCode: \"123\",","    shouldTokenize: true,",")"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you already have a credit card token, you can then set up token payment omitting credit card"},{"type":"text","text":" "},{"type":"text","text":"info."},{"type":"text","text":" "},{"type":"text","text":"To do so, use "},{"code":"Tpay.Headless.Models.CardToken","type":"codeVoice"},{"type":"text","text":" class instead of "},{"code":"Tpay.Headless.Models.Card","type":"codeVoice"},{"type":"text","text":" one."}]},{"syntax":"swift","code":["do {","    try Headless.invokePayment(","        for: SingleTransaction(","            amount: 250,","            description: \"test\",","            hiddenDescription: \"hidden message\",","            payerContext: PayerContext(","                payer: Payer(","                    name: \"Test\",","                    email: \"email@address.com\",","                ),","            ),","        ),","        using: chosenPaymentChannel,","        with: Tpay.Headless.Models.CardToken(","            token: \"saved_card_token\",","            cardTail: \"1234\",","            brand: CardToken.Brand.visa,","        )","    ) { result in","        switch result {","        case .success(let paymentResult):","            \/\/ Handle payment result","        case .failure(let error):","            \/\/ Handle payment error","        }","    }","} catch {","    \/\/ Handle invocation errors or other exceptions","}"],"type":"codeListing"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"[!Warning]","type":"text"},{"text":" ","type":"text"},{"text":"For recurring payments, you can simply use created token in the haedless payments","type":"text"},{"text":" ","type":"text"},{"text":"to make transaction without need of user interaction.","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/tpay\/cardtokenization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tpay\/cardtokenization"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCard\/Sheet"],"anchor":"Classes"}],"hierarchy":{"paths":[["doc:\/\/com.tpay.sdk\/documentation\/Tpay"]]},"abstract":[{"type":"text","text":"Saving credit card details for future purchases."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization"},"metadata":{"modules":[{"name":"Tpay"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Card tokenization"},"seeAlsoSections":[{"title":"Use cases","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments"],"anchor":"Use-cases","generated":true}],"references":{"doc://com.tpay.sdk/documentation/Tpay/AutomaticPayments":{"title":"Automatic payments","kind":"article","role":"article","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments","type":"topic","url":"\/documentation\/tpay\/automaticpayments","abstract":[{"type":"text","text":"Providing automatic payment methods for a specific payer."}]},"doc://com.tpay.sdk/documentation/Tpay/Payment":{"title":"Payment","kind":"article","role":"article","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","type":"topic","url":"\/documentation\/tpay\/payment","abstract":[{"type":"text","text":"Creating and processing payment transactions."}]},"doc://com.tpay.sdk/documentation/Tpay":{"role":"collection","kind":"symbol","abstract":[],"title":"Tpay","type":"topic","url":"\/documentation\/tpay","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay"},"doc://com.tpay.sdk/documentation/Tpay/AddCard/Sheet":{"type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCard\/Sheet","url":"\/documentation\/tpay\/addcard\/sheet","navigatorTitle":[{"kind":"identifier","text":"Sheet"}],"kind":"symbol","title":"AddCard.Sheet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sheet"}],"abstract":[{"code":"AddCard.Sheet","type":"codeVoice"},{"type":"text","text":" is a component that provides a user interface for adding a new card for future payment. It is designed to be presented as a sheet within your application and facilitates the tokenization of credit card information for future transactions."}],"role":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/AddCard/Sheet/present(from:)":{"title":"present(from:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Presents the sheet from a specified view controller."}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCard\/Sheet\/present(from:)","url":"\/documentation\/tpay\/addcard\/sheet\/present(from:)"},"doc://com.tpay.sdk/documentation/Tpay/AddCardDelegate":{"role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddCardDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AddCardDelegate"},{"type":"text","text":" protocol defines the methods that a delegate should implement to handle events related to card tokenization."}],"url":"\/documentation\/tpay\/addcarddelegate","type":"topic","title":"AddCardDelegate","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AddCardDelegate","navigatorTitle":[{"text":"AddCardDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments"],"generated":true,"title":"Use cases","anchor":"Use-cases"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}