{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tpay\/installation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tpay\/installation"]}],"hierarchy":{"paths":[["doc:\/\/com.tpay.sdk\/documentation\/Tpay"]]},"abstract":[{"text":"How to install the SDK.","type":"text"}],"seeAlsoSections":[{"title":"Getting started","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics"],"generated":true,"anchor":"Getting-started"}],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"content":[{"text":"Integrating Tpay using SPM","type":"heading","anchor":"Integrating-Tpay-using-SPM","level":2},{"syntax":null,"type":"codeListing","code":["File > Swift Packages > Add Package Dependency","Add https:\/\/github.com\/tpay-com\/tpay-ios.git","Select \"Up to Next Major\" with \"1.0.0\""]},{"text":"Integrating Tpay using CocoaPods","type":"heading","anchor":"Integrating-Tpay-using-CocoaPods","level":2},{"syntax":"ruby","type":"codeListing","code":["use_frameworks!","","target :MyTarget do","  pod 'Tpay-SDK'","end"]},{"inlineContent":[{"type":"text","text":"Once you have completed your Podfile, simply run "},{"code":"pod install","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"text":"Integrating Tpay manually","type":"heading","anchor":"Integrating-Tpay-manually","level":2},{"inlineContent":[{"type":"text","text":"Simply, drag the "},{"code":"Tpay.xcframework","type":"codeVoice"},{"type":"text","text":" into the "},{"code":"Frameworks, Libraries and Embedded Content","type":"codeVoice"},{"type":"text","text":" section of your target."}],"type":"paragraph"},{"text":"Import","type":"heading","anchor":"Import","level":2},{"inlineContent":[{"type":"text","text":"To begin, make sure you have imported the "},{"code":"Tpay","type":"codeVoice"},{"type":"text","text":" framework into your project. You can do this by adding the following line at the top of your Swift file:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["import Tpay"]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation"},"metadata":{"roleHeading":"Article","title":"Installation","modules":[{"name":"Tpay"}],"role":"article"},"references":{"doc://com.tpay.sdk/documentation/Tpay/Basics":{"title":"Basics","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics","type":"topic","role":"article","url":"\/documentation\/tpay\/basics","kind":"article","abstract":[{"type":"text","text":"How to start."}]},"doc://com.tpay.sdk/documentation/Tpay/Permissions":{"kind":"article","type":"topic","abstract":[{"type":"text","text":"Required app permissions."}],"role":"article","url":"\/documentation\/tpay\/permissions","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions","title":"Permissions"},"doc://com.tpay.sdk/documentation/Tpay":{"kind":"symbol","type":"topic","abstract":[],"role":"collection","url":"\/documentation\/tpay","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay","title":"Tpay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Getting started","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics"],"anchor":"Getting-started","generated":true}],"op":"replace"}]}]}