{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tpay\/payment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tpay\/payment"]}],"metadata":{"modules":[{"name":"Tpay"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Payment"},"abstract":[{"type":"text","text":"Creating and processing payment transactions."}],"hierarchy":{"paths":[["doc:\/\/com.tpay.sdk\/documentation\/Tpay"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"content":[{"anchor":"Create-a-transaction","level":2,"type":"heading","text":"Create a transaction"},{"inlineContent":[{"text":"You can create a transaction using the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SingleTransaction","type":"reference"},{"text":" struct specifying the transaction’s amount and description.","type":"text"}],"type":"paragraph"},{"code":["let singleTransaction = SingleTransaction(amount: 50.0, description: \"Product Purchase\")"],"type":"codeListing","syntax":"swift"},{"anchor":"Payer-context","level":3,"type":"heading","text":"Payer context"},{"inlineContent":[{"text":"The payer context provides information about the payer, including their personal details and automatic payment methods. You can pass it along with transaction details.","type":"text"}],"type":"paragraph"},{"code":["let payer = Payer(name: \"John Doe\", email: \"john@example.com\")","let payerContext = PayerContext(payer: payer, automaticPaymentMethods: nil)","let singleTransaction = SingleTransaction(amount: 50.0, description: \"Product Purchase\", payerContext: payerContext)"],"type":"codeListing","syntax":"swift"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPaymentMethods","isActive":true},{"text":" page describing how to provide automatic payment methods for a specific payer.","type":"text"}]}],"type":"aside","name":"Note"},{"anchor":"Recursive-transaction","level":3,"type":"heading","text":"Recursive transaction"},{"inlineContent":[{"type":"text","text":"For recurring transactions, you shall create an instance of "},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/RecursiveTransaction","type":"reference","isActive":true},{"type":"text","text":" specifying recursion parameters such as the frequency, quantity, and expiry date."}],"type":"paragraph"},{"code":["let recursiveTransaction = RecursiveTransaction(wrapping: singleTransaction,","                                                frequency: .monthly,","                                                quantity: .count(5),","                                                expiryDate: futureDate)"],"type":"codeListing","syntax":"swift"},{"anchor":"Payment-sheet","level":2,"type":"heading","text":"Payment sheet"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/Sheet","type":"reference","isActive":true},{"type":"text","text":" is designed to guide the user through the payment process. Payment sheet is presented in a modal style, providing a focused and intuitive payment interaction. The class interacts with the provided "},{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentDelegate","type":"reference","isActive":true},{"type":"text","text":" to notify about payment events."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To create an instance of the "},{"code":"Sheet","type":"codeVoice"},{"type":"text","text":" class, initialize it with a "},{"code":"Transaction","type":"codeVoice"},{"type":"text","text":" object and an optional "},{"code":"PaymentDelegate","type":"codeVoice"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","code":["let paymentSheet = Payment.Sheet(transaction: transaction, delegate: delegate)"],"syntax":"swift"},{"inlineContent":[{"type":"text","text":"Use the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/Sheet\/present(from:)"},{"type":"text","text":" method to present the payment sheet from a view controller:"}],"type":"paragraph"},{"type":"codeListing","code":["do {","    try paymentSheet.present(from: presentingViewController)","} catch {","    \/\/ Handle configuration errors or other exceptions","}"],"syntax":"swift"},{"inlineContent":[{"text":"To dismiss the payment sheet manually, call the ","type":"text"},{"code":"dismiss()","type":"codeVoice"},{"text":" method:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["paymentSheet.dismiss()"],"syntax":"swift"},{"level":3,"type":"heading","text":"SwiftUI way","anchor":"SwiftUI-way"},{"type":"codeListing","code":["struct ContentView: View {","    @State private var isPaymentSheetPresented = false","","    var body: some View {","        Button(\"Pay\") {","            isPaymentSheetPresented.toggle()","        }","        .presentPaymentSheet(for: transaction, isPresented: $isPaymentSheetPresented) { transactionId in","            \/\/ Handle payment completed","        } onPaymentCancelled: { transactionId in","            \/\/ Handle payment cancelled","        } onErrorOccured: { error in","            \/\/ Handle payment error","        }","    }","}"],"syntax":"swift"},{"level":2,"type":"heading","text":"Headless","anchor":"Headless"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An alternative method for incorporating payments into an application is available. This approach empowers developers to autonomously gather all necessary payer information, facilitating the invocation of methods to programmatically initiate and advance through payment transactions, all without relying on a dedicated user interface (Payment Sheet)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Initially, retrieve the list of available payment channels:"}]},{"type":"codeListing","syntax":"swift","code":["Headless.getAvailablePaymentChannels { result in","    switch result {","    case .success(let paymentChannels):","        \/\/ Handle available payment channels","    case .failure(let error):","        \/\/ Handle error","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once you have the list of available payment channels, choose the desired channel and execute the relevant method with the appropriate arguments:"}]},{"type":"codeListing","syntax":"swift","code":["do {","    Headless.invokePayment(for: transaction, using: cardPaymentChannel, with: card) { result in","        switch result {","        case .success(let paymentResult):","            \/\/ Handle payment result","        case .failure(let error):","            \/\/ Handle error","        }","    }","} catch {","    \/\/ Handle invocation errors or other exceptions","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After successful payment invocation, you can retrieve the current payment status using:"}]},{"type":"codeListing","syntax":"swift","code":["Headless.getPaymentStatus(for: paymentResult.ongoingTransaction) { statusResult in","    switch statusResult {","    case .success(let paymentStatus):","        \/\/ Handle payment status","    case .failure(let statusError):","        \/\/ Handle status retrieval error","    }","}"]},{"type":"heading","level":2,"anchor":"Payment-WebView","text":"Payment WebView"},{"type":"paragraph","inlineContent":[{"text":"You can easily handle externally generated transactions with a WebView component.","type":"text"},{"text":" ","type":"text"},{"text":"In order to generate a tranaction, please follow ","type":"text"},{"code":"Transactions","type":"codeVoice"},{"text":" section under ","type":"text"},{"type":"reference","identifier":"https:\/\/openapi.tpay.com","isActive":true},{"text":".","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let transaction = ExternallyGeneratedTransaction(transactionPaymentUrl: transactionPaymentUrl,  \/\/ retrieved from POST \/transactions","                                                 onSuccessRedirectUrl: onSuccessUrl,            \/\/ must match the one sent on transaction create","                                                 onErrorRedirectUrl: onErrorUrl)                \/\/ must match the one sent on transaction create","","let paymentWebView = Payment.WebView(transaction: transaction, delegate: delegate)","do {","    try paymentWebView?.present(from: self)","} catch {","    \/\/ Handle configuration errors or other exceptions","}"]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment","interfaceLanguage":"swift"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Headless"],"anchor":"Topics"},{"title":"Classes","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/Sheet","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/Button","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/WebView"],"anchor":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentDelegate"],"anchor":"Protocols"}],"seeAlsoSections":[{"title":"Use cases","generated":true,"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments"],"anchor":"Use-cases"}],"references":{"doc://com.tpay.sdk/documentation/Tpay/CardTokenization":{"url":"\/documentation\/tpay\/cardtokenization","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","abstract":[{"type":"text","text":"Saving credit card details for future purchases."}],"role":"collectionGroup","type":"topic","title":"Card tokenization","kind":"article"},"doc://com.tpay.sdk/documentation/Tpay/RecursiveTransaction":{"abstract":[{"type":"text","text":"The "},{"code":"RecursiveTransaction","type":"codeVoice"},{"type":"text","text":" struct represents a recursive transaction. It extends a specified transaction object with recursion parameters such as the frequency, quantity, and expiry date."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecursiveTransaction","kind":"identifier"}],"kind":"symbol","title":"RecursiveTransaction","url":"\/documentation\/tpay\/recursivetransaction","type":"topic","navigatorTitle":[{"text":"RecursiveTransaction","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/RecursiveTransaction"},"doc://com.tpay.sdk/documentation/Tpay/Payment/Sheet/present(from:)":{"url":"\/documentation\/tpay\/payment\/sheet\/present(from:)","type":"topic","abstract":[{"type":"text","text":"Presents the payment sheet from a specified view controller."}],"role":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/Sheet\/present(from:)","kind":"symbol","title":"present(from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"https://openapi.tpay.com":{"title":"OpenAPI documentation","type":"link","identifier":"https:\/\/openapi.tpay.com","titleInlineContent":[{"type":"text","text":"OpenAPI documentation"}],"url":"https:\/\/openapi.tpay.com"},"doc://com.tpay.sdk/documentation/Tpay/AutomaticPayments":{"type":"topic","title":"Automatic payments","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments","abstract":[{"type":"text","text":"Providing automatic payment methods for a specific payer."}],"role":"article","kind":"article","url":"\/documentation\/tpay\/automaticpayments"},"doc://com.tpay.sdk/documentation/Tpay/SingleTransaction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleTransaction"}],"url":"\/documentation\/tpay\/singletransaction","title":"SingleTransaction","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/SingleTransaction","abstract":[{"type":"text","text":"The "},{"code":"SingleTransaction","type":"codeVoice"},{"type":"text","text":" struct represents a single transaction with associated properties such as the transaction amount, description, and payer context."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SingleTransaction"}],"type":"topic"},"doc://com.tpay.sdk/documentation/Tpay/Payment/Sheet":{"role":"symbol","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/Sheet","navigatorTitle":[{"text":"Sheet","kind":"identifier"}],"type":"topic","title":"Payment.Sheet","abstract":[{"text":"The ","type":"text"},{"code":"Payment.Sheet","type":"codeVoice"},{"text":" class provides a streamlined way to present payment transactions within your app.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sheet","kind":"identifier"}],"url":"\/documentation\/tpay\/payment\/sheet"},"doc://com.tpay.sdk/documentation/Tpay/Payment/WebView":{"kind":"symbol","type":"topic","title":"Payment.WebView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WebView","kind":"identifier"}],"navigatorTitle":[{"text":"WebView","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/WebView","url":"\/documentation\/tpay\/payment\/webview","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"WebView"},{"text":" class provides functionality for presenting a web view for externally-generated transaction processing within the payment module.","type":"text"}],"role":"symbol"},"doc://com.tpay.sdk/documentation/Tpay/Payment/Button":{"kind":"symbol","url":"\/documentation\/tpay\/payment\/button","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Payment\/Button","role":"symbol","title":"Payment.Button","navigatorTitle":[{"text":"Button","kind":"identifier"}],"abstract":[{"type":"text","text":"The specialized UIButton designed to serve as an effortless entry point for invoking the payment sheet within your app."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Button","kind":"identifier"}]},"doc://com.tpay.sdk/documentation/Tpay":{"url":"\/documentation\/tpay","type":"topic","abstract":[],"title":"Tpay","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay","kind":"symbol","role":"collection"},"doc://com.tpay.sdk/documentation/Tpay/PaymentDelegate":{"title":"PaymentDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/PaymentDelegate","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PaymentDelegate"},{"type":"text","text":" protocol defines the methods that a delegate should implement to handle payment-related events."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PaymentDelegate","kind":"identifier"}],"url":"\/documentation\/tpay\/paymentdelegate"},"doc://com.tpay.sdk/documentation/Tpay/Headless":{"identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Headless","title":"Headless","abstract":[{"text":"The ","type":"text"},{"code":"Headless","type":"codeVoice"},{"text":" API provides functionality for performing headless (without using Payment Sheet) transactions and handling payment-related operations. Developers can use this API to create and manage transactions independently, catering to specific use cases or custom user interfaces.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Headless","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Headless","kind":"identifier"}],"url":"\/documentation\/tpay\/headless"},"doc://com.tpay.sdk/documentation/Tpay/AutomaticPaymentMethods":{"navigatorTitle":[{"kind":"identifier","text":"AutomaticPaymentMethods"}],"kind":"symbol","title":"AutomaticPaymentMethods","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomaticPaymentMethods"}],"abstract":[{"type":"text","text":"The "},{"code":"AutomaticPaymentMethods","type":"codeVoice"},{"type":"text","text":" struct represents a collection of automatic payment methods associated with a concrete payer."}],"type":"topic","url":"\/documentation\/tpay\/automaticpaymentmethods","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPaymentMethods"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Use-cases","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/CardTokenization","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/AutomaticPayments"],"title":"Use cases"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}