{"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When integrating the Tpay payment module into your app, it’s important to ensure that the necessary permissions are correctly set up to ensure a smooth user experience."}]},{"type":"heading","level":2,"text":"Privacy - Camera Usage Description","anchor":"Privacy-Camera-Usage-Description"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The module allows the user to automatically fill the credit card form for secure payment processing. This feature requires you to setup the “Privacy - Camera Usage Description” in your app’s "},{"code":"Info.plist","type":"codeVoice"},{"type":"text","text":" file."}]},{"type":"heading","level":3,"text":"Integration Steps","anchor":"Integration-Steps"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Open your project’s ","type":"text"},{"code":"Info.plist","type":"codeVoice"},{"text":" file.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Add the key-value pair for the “Privacy - Camera Usage Description” permission, explaining the purpose of camera access. Clearly state that the camera is used to facilitate the automatic filling of the credit card form for secure payment processing.","type":"text"}]}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"code":["<key>NSCameraUsageDescription<\/key>","<string>We need access to your camera to automatically fill the credit card form for secure payment processing.<\/string>"],"type":"codeListing","syntax":"xml"}],"kind":"content"}],"metadata":{"roleHeading":"Article","modules":[{"name":"Tpay"}],"role":"article","title":"Permissions"},"hierarchy":{"paths":[["doc:\/\/com.tpay.sdk\/documentation\/Tpay"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Permissions"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tpay\/permissions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tpay\/permissions"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics"],"title":"Getting started","generated":true,"anchor":"Getting-started"}],"sections":[],"abstract":[{"type":"text","text":"Required app permissions."}],"references":{"doc://com.tpay.sdk/documentation/Tpay":{"role":"collection","title":"Tpay","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay","kind":"symbol","url":"\/documentation\/tpay","abstract":[]},"doc://com.tpay.sdk/documentation/Tpay/Basics":{"role":"article","title":"Basics","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics","kind":"article","url":"\/documentation\/tpay\/basics","abstract":[{"text":"How to start.","type":"text"}]},"doc://com.tpay.sdk/documentation/Tpay/Installation":{"role":"article","title":"Installation","type":"topic","identifier":"doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","kind":"article","url":"\/documentation\/tpay\/installation","abstract":[{"text":"How to install the SDK.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting started","identifiers":["doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Installation","doc:\/\/com.tpay.sdk\/documentation\/Tpay\/Basics"],"generated":true,"anchor":"Getting-started"}]}]}]}