name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version  (ie 5.5.0)'
        required: true

jobs:
  create_release:
    runs-on: macos-13
    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Config Git
      run: |
        git config user.name "Tpay Auto Commit"
        git config user.email devs@tpay.com

    - name: Create release branch
      run: git checkout -b release/${{ github.event.inputs.version }}

    - name: Install pods
      run: bundle exec pod install

    - name: Prepeare release
      env:
        GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        GITHUB_REPOSITORY_NAME: ${{ github.repository }}
      run: bundle exec fastlane prepare_release version:${{ github.event.inputs.version }}

    - name: Update docs
      env:
        HOSTING_BASE_PATH: ${{ github.event.repository.name }}
      run: |
        sh scripts/generate_docs.sh
        git add docs/
        git commit --message "Update docs"

    - name: Push release branch
      run: git push origin release/${{ github.event.inputs.version }}

    - name: Create pull request into master
      uses: thomaseizinger/create-pull-request@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        head: release/${{ github.event.inputs.version }}
        base: master
        title: ${{ github.event.inputs.version }} into master