name: Run tests

on: workflow_dispatch

jobs:  
  unit_test:
    runs-on: macos-26
    env:
      XCODE_PATH: /Applications/Xcode_26.4.app
    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Install pods
      run: bundle exec pod install

    - name: Unit tests
      run: bundle exec fastlane test