name: Run tests

on: workflow_dispatch

jobs:  
  unit_test:
    runs-on: macos-13
    timeout-minutes: 29
    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Install pods
      run: bundle exec pod install

    - name: Unit tests
      run: bundle exec fastlane test